name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Testing Extensions
      run: php -m
    - run: apt-get update
    - name: Composer install
      run: |
        composer install
    - run: php artisan migrate --force
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
    - name: Code Checks
      run: ./.deploy/commands/phpunit.sh
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        APP_KEY: ${{ secrets.APP_KEY }}
